# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AppClip' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AppClip

end

target 'AppClipExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AppClipExample

end
